version: '3'

services:
  namahamu-melon:
    image: namahamu-melon
    build: .
    cap_add:
      - SYS_ADMIN
    environment:
      - CHROME_EXECUTE_PATH=google-chrome-unstable
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
