version: '3'

services:
  namahamu-melon:
    image: ghcr.io/windyakin/namahamu-melon
    build: .
    cap_add:
      - SYS_ADMIN
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
