name: Build Docker image

on:
  push:
    branches:
    pull_requests:

jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: ghcr.io/windyakin/namahamu-melon:latest
          push: false
