name: Publish to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          tags: ghcr.io/windyakin/namahamu-melon:latest
          push: true
